name: build-feature

on: workflow_dispatch

env:
  ARCH_KEYSTORE: ${{ secrets.ARCHIVED_KEYSTORE }}
  KEY_PASS: ${{ secrets.KEY_PASS }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  BUNDLE_TOOL: bundletool.jar
  KEYSTORE: keystore

jobs:
  # Builds release bundle.
  build-bundle:
    uses: ./.github/workflows/build-bundle.yml

  generate-apk:
    runs-on: ubuntu-latest
    needs: [build-bundle]
    steps:

      # Download Java runtime to run bundle tool.
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'liberica'
          java-package: 'jre'

      - name: Download Bundle Tool
        # Single command written in multiline manner.
        # -4 dictates to use only IPv4. -L dictates to redo request if resource was moved.
        run: |
          curl \
            'https://github.com/google/bundletool/releases/download/1.8.1/bundletool-all-1.8.1.jar' \
            -4 \
            -sL \
            -o bundletool.jar

      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Download built bundle
        uses: actions/download-artifact@v3
        with:
          name: app-release.aab
          path: .

      - name: Get keystore
        run: |
          encodedZipFile="encodedKey.txt"
          echo $ARCH_KEYSTORE > "$encodedZipFile"
          ./secret_parser.sh -d "$encodedZipFile" keystore

      - name: Generate apk file
        run: |
          ls -l bundletool.jar
          
          universalApk=release_app.apk
          apksFile="app.apks"
          java -jar bundletool.jar build-apks \
            --mode=universal \
            --local-testing \
            --bundle app-release.aab \
            --output "$apksFile" \
            --ks=keystore \
            --ks-pass=pass:"$KEY_PASS" \
            --ks-key-alias="$KEY_ALIAS" \
            --key-pass=pass:"$KEY_PASS"
          unzip -p "$apksFile" universal.apk > $universalApk

      - name: Upload universal apk to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: release-app.apk
          path: release_app.apk