name: build-bundle
on: workflow_call
jobs:
  setup-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'liberica'
      # This task enables gradle caching between flow executions. Also it can execute gradle commands.
      # Additional use: just add this task to setup gradle cache and all. Execute any gradlew commands afterwards.
      # Uses gradle-wrapper by default. User may also specify exact version to run builds upon.
      - name: Setup gradle caching
        uses: gradle/gradle-build-action@v2
      # If flow runs on a non-default GitHub branch then cache saving needs to be enabled via 'cache-read-only: false'!
        with:
          cache-read-only: false

  checkout-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest commit from ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Check Gradle Wrapper authenticity
      # Use exact commit instead of version tag for better security.
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

  build-bundle:
    needs: [setup-tools, checkout-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Build release bundle
        run: ./gradlew bundleRelease
