name: release-build
on:
  push:
   branches:
     - 'release/**'
jobs:
  # If job uses reusable workflow it cannot have its own steps.
  release-build:
    uses: ./.github/workflows/build-bundle.yml

#         Bundle Tool downloading
#          curl --location 'https://github.com/google/bundletool/releases/download/1.8.1/bundletool-all-1.8.1.jar' --output bundletool.jar
