name: release-build
on:
  push:
   branches:
     - 'release/**'
jobs:
  # Job called "build" is specified here.
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow run count
        run: echo $GITHUB_RUN_NUMBER
      # Job steps can be named
      - name: Check out latest commit from ${{ github.ref }}
        uses: actions/checkout@v3
      # This one allows to install specific java version.
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
#          distribution: 'liberica'
          distribution: 'corretto'
      # We'll try to use preinstalled java distribution on a runner.
      - name: Validate Gradle wrapper from branch
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      # This task enables gradle caching between flow executions. Also it can execute gradle commands.
      # Additional use: just add this task to setup gradle cache and all. Execute any gradlew commands afterwards.
      # Uses gradle-wrapper by default. User may also specify exact version to run builds upon.
      - name: Gradle setup
        uses: gradle/gradle-build-action@v2
      # If flow runs on a non-default GitHub branch then cache saving needs to be enabled via 'cache-read-only: false'!
        with:
          cache-read-only: false
      - name: Build release bundle
        run: ./gradlew bundleRelease
      - name: Uploading app to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab
